// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CallLog.proto

package com.amir.hbase.util;

public final class CallLogOuterClass {
    private CallLogOuterClass() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface CallLogOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.amir.hbase.util.CallLog)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 length = 1;</code>
         * @return The length.
         */
        int getLength();

        /**
         * <code>string dnum = 2;</code>
         * @return The dnum.
         */
        java.lang.String getDnum();
        /**
         * <code>string dnum = 2;</code>
         * @return The bytes for dnum.
         */
        com.google.protobuf.ByteString
        getDnumBytes();

        /**
         * <code>int32 type = 3;</code>
         * @return The type.
         */
        int getType();

        /**
         * <code>string date = 4;</code>
         * @return The date.
         */
        java.lang.String getDate();
        /**
         * <code>string date = 4;</code>
         * @return The bytes for date.
         */
        com.google.protobuf.ByteString
        getDateBytes();
    }
    /**
     * Protobuf type {@code com.amir.hbase.util.CallLog}
     */
    public static final class CallLog extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.amir.hbase.util.CallLog)
            CallLogOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use CallLog.newBuilder() to construct.
        private CallLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private CallLog() {
            dnum_ = "";
            date_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new CallLog();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private CallLog(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            length_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            dnum_ = s;
                            break;
                        }
                        case 24: {

                            type_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            date_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.amir.hbase.util.CallLogOuterClass.internal_static_com_amir_hbase_util_CallLog_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.amir.hbase.util.CallLogOuterClass.internal_static_com_amir_hbase_util_CallLog_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.amir.hbase.util.CallLogOuterClass.CallLog.class, com.amir.hbase.util.CallLogOuterClass.CallLog.Builder.class);
        }

        public static final int LENGTH_FIELD_NUMBER = 1;
        private int length_;
        /**
         * <code>int32 length = 1;</code>
         * @return The length.
         */
        @java.lang.Override
        public int getLength() {
            return length_;
        }

        public static final int DNUM_FIELD_NUMBER = 2;
        private volatile java.lang.Object dnum_;
        /**
         * <code>string dnum = 2;</code>
         * @return The dnum.
         */
        @java.lang.Override
        public java.lang.String getDnum() {
            java.lang.Object ref = dnum_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                dnum_ = s;
                return s;
            }
        }
        /**
         * <code>string dnum = 2;</code>
         * @return The bytes for dnum.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getDnumBytes() {
            java.lang.Object ref = dnum_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dnum_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TYPE_FIELD_NUMBER = 3;
        private int type_;
        /**
         * <code>int32 type = 3;</code>
         * @return The type.
         */
        @java.lang.Override
        public int getType() {
            return type_;
        }

        public static final int DATE_FIELD_NUMBER = 4;
        private volatile java.lang.Object date_;
        /**
         * <code>string date = 4;</code>
         * @return The date.
         */
        @java.lang.Override
        public java.lang.String getDate() {
            java.lang.Object ref = date_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                date_ = s;
                return s;
            }
        }
        /**
         * <code>string date = 4;</code>
         * @return The bytes for date.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getDateBytes() {
            java.lang.Object ref = date_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                date_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (length_ != 0) {
                output.writeInt32(1, length_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dnum_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dnum_);
            }
            if (type_ != 0) {
                output.writeInt32(3, type_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, date_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (length_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, length_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dnum_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dnum_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, type_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, date_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.amir.hbase.util.CallLogOuterClass.CallLog)) {
                return super.equals(obj);
            }
            com.amir.hbase.util.CallLogOuterClass.CallLog other = (com.amir.hbase.util.CallLogOuterClass.CallLog) obj;

            if (getLength()
                    != other.getLength()) return false;
            if (!getDnum()
                    .equals(other.getDnum())) return false;
            if (getType()
                    != other.getType()) return false;
            if (!getDate()
                    .equals(other.getDate())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + LENGTH_FIELD_NUMBER;
            hash = (53 * hash) + getLength();
            hash = (37 * hash) + DNUM_FIELD_NUMBER;
            hash = (53 * hash) + getDnum().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + DATE_FIELD_NUMBER;
            hash = (53 * hash) + getDate().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.amir.hbase.util.CallLogOuterClass.CallLog parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.amir.hbase.util.CallLogOuterClass.CallLog prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.amir.hbase.util.CallLog}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.amir.hbase.util.CallLog)
                com.amir.hbase.util.CallLogOuterClass.CallLogOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.amir.hbase.util.CallLogOuterClass.internal_static_com_amir_hbase_util_CallLog_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.amir.hbase.util.CallLogOuterClass.internal_static_com_amir_hbase_util_CallLog_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.amir.hbase.util.CallLogOuterClass.CallLog.class, com.amir.hbase.util.CallLogOuterClass.CallLog.Builder.class);
            }

            // Construct using com.amir.hbase.util.CallLogOuterClass.CallLog.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                length_ = 0;

                dnum_ = "";

                type_ = 0;

                date_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.amir.hbase.util.CallLogOuterClass.internal_static_com_amir_hbase_util_CallLog_descriptor;
            }

            @java.lang.Override
            public com.amir.hbase.util.CallLogOuterClass.CallLog getDefaultInstanceForType() {
                return com.amir.hbase.util.CallLogOuterClass.CallLog.getDefaultInstance();
            }

            @java.lang.Override
            public com.amir.hbase.util.CallLogOuterClass.CallLog build() {
                com.amir.hbase.util.CallLogOuterClass.CallLog result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public com.amir.hbase.util.CallLogOuterClass.CallLog buildPartial() {
                com.amir.hbase.util.CallLogOuterClass.CallLog result = new com.amir.hbase.util.CallLogOuterClass.CallLog(this);
                result.length_ = length_;
                result.dnum_ = dnum_;
                result.type_ = type_;
                result.date_ = date_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.amir.hbase.util.CallLogOuterClass.CallLog) {
                    return mergeFrom((com.amir.hbase.util.CallLogOuterClass.CallLog)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.amir.hbase.util.CallLogOuterClass.CallLog other) {
                if (other == com.amir.hbase.util.CallLogOuterClass.CallLog.getDefaultInstance()) return this;
                if (other.getLength() != 0) {
                    setLength(other.getLength());
                }
                if (!other.getDnum().isEmpty()) {
                    dnum_ = other.dnum_;
                    onChanged();
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (!other.getDate().isEmpty()) {
                    date_ = other.date_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.amir.hbase.util.CallLogOuterClass.CallLog parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.amir.hbase.util.CallLogOuterClass.CallLog) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int length_ ;
            /**
             * <code>int32 length = 1;</code>
             * @return The length.
             */
            @java.lang.Override
            public int getLength() {
                return length_;
            }
            /**
             * <code>int32 length = 1;</code>
             * @param value The length to set.
             * @return This builder for chaining.
             */
            public Builder setLength(int value) {

                length_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 length = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearLength() {

                length_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object dnum_ = "";
            /**
             * <code>string dnum = 2;</code>
             * @return The dnum.
             */
            public java.lang.String getDnum() {
                java.lang.Object ref = dnum_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    dnum_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string dnum = 2;</code>
             * @return The bytes for dnum.
             */
            public com.google.protobuf.ByteString
            getDnumBytes() {
                java.lang.Object ref = dnum_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    dnum_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string dnum = 2;</code>
             * @param value The dnum to set.
             * @return This builder for chaining.
             */
            public Builder setDnum(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                dnum_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string dnum = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearDnum() {

                dnum_ = getDefaultInstance().getDnum();
                onChanged();
                return this;
            }
            /**
             * <code>string dnum = 2;</code>
             * @param value The bytes for dnum to set.
             * @return This builder for chaining.
             */
            public Builder setDnumBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                dnum_ = value;
                onChanged();
                return this;
            }

            private int type_ ;
            /**
             * <code>int32 type = 3;</code>
             * @return The type.
             */
            @java.lang.Override
            public int getType() {
                return type_;
            }
            /**
             * <code>int32 type = 3;</code>
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 type = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object date_ = "";
            /**
             * <code>string date = 4;</code>
             * @return The date.
             */
            public java.lang.String getDate() {
                java.lang.Object ref = date_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    date_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string date = 4;</code>
             * @return The bytes for date.
             */
            public com.google.protobuf.ByteString
            getDateBytes() {
                java.lang.Object ref = date_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    date_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string date = 4;</code>
             * @param value The date to set.
             * @return This builder for chaining.
             */
            public Builder setDate(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                date_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string date = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearDate() {

                date_ = getDefaultInstance().getDate();
                onChanged();
                return this;
            }
            /**
             * <code>string date = 4;</code>
             * @param value The bytes for date to set.
             * @return This builder for chaining.
             */
            public Builder setDateBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                date_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:com.amir.hbase.util.CallLog)
        }

        // @@protoc_insertion_point(class_scope:com.amir.hbase.util.CallLog)
        private static final com.amir.hbase.util.CallLogOuterClass.CallLog DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.amir.hbase.util.CallLogOuterClass.CallLog();
        }

        public static com.amir.hbase.util.CallLogOuterClass.CallLog getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<CallLog>
                PARSER = new com.google.protobuf.AbstractParser<CallLog>() {
            @java.lang.Override
            public CallLog parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new CallLog(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<CallLog> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<CallLog> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public com.amir.hbase.util.CallLogOuterClass.CallLog getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_amir_hbase_util_CallLog_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_amir_hbase_util_CallLog_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rCallLog.proto\022\023com.amir.hbase.util\"C\n\007" +
                        "CallLog\022\016\n\006length\030\001 \001(\005\022\014\n\004dnum\030\002 \001(\t\022\014\n" +
                        "\004type\030\003 \001(\005\022\014\n\004date\030\004 \001(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_com_amir_hbase_util_CallLog_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_amir_hbase_util_CallLog_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_amir_hbase_util_CallLog_descriptor,
                new java.lang.String[] { "Length", "Dnum", "Type", "Date", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
